spring:
  profiles:
    active: prod

server:
  tomcat:
    accesslog:
      enabled: true
  port: 9999
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:nms
    username: admin
    password:
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
    console.path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration/h2
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${URL}
    username: ${USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration/postgres
---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:postgresql://suleiman.db.elephantsql.com:5432/uxcbzsmy
    username: uxcbzsmy
    password: UGf8nyog_kPYrgY5Y9gXw40HZOZi0-7P
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration/mysql
